export enum ProductCategoryEnum {
  LARGE_APPLIANCES = 'LARGE_APPLIANCES',
  SMALL_APPLIANCES = 'SMALL_APPLIANCES',
  MOBILE_DEVICES = 'MOBILE_DEVICES',
  ELECTRONICS = 'ELECTRONICS',
  ACCESSORIES = 'ACCESSORIES',
}
